config/routes.rb
Chesswin::Application.routes.draw do
  resources :casestudies
  resources :pages

  namespace :admin do 
  	resources :users 
  	resources :casestudies do
  		resources :photos
  	end
  	resources :photos
  end

  root :to => 'pages#index'

  
  match ':controller(/:action(/:id))(.:format)'
  
  match 'login'			=> 'users#login'
  match 'logout'		=> 'users#logout'
  
end

app/models/casestudy.rb
class Casestudy < ActiveRecord::Base
	has_many :photos
	attr_accessible :active_time, :active_time_end, :category, :client, :content, :invitation, :photos, :place, :subtitle, :title
end

app/controllers/admin/casestudies_controller.rb
#encoding: utf-8
class Admin::CasestudiesController < AdminController
  # GET /casestudies
  # GET /casestudies.json
  def index
    @casestudies = Casestudy.order( "created_at DESC" ).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @casestudies }
    end
  end

  # GET /casestudies/1
  # GET /casestudies/1.json
  def show
    @casestudy = Casestudy.find(params[:id])
    @photos = @casestudy.photos.order( :created_at )

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @casestudy }
    end
  end

  # GET /casestudies/new
  # GET /casestudies/new.json
  def new
    @casestudy = Casestudy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @casestudy }
    end
  end

  # GET /casestudies/1/edit
  def edit
    @casestudy = Casestudy.find(params[:id])
    @photos = @casestudy.photos.order( :created_at => "desc" )
  end

  # POST /casestudies
  # POST /casestudies.json
  def create
  
    @casestudy = Casestudy.new(params[:casestudy])

    respond_to do |format|
      if @casestudy.save
        format.html { redirect_to edit_admin_casestudy_path(@casestudy), notice: '成功案例建立完成。' }
        format.json { render json: @casestudy, status: :created, location: @casestudy }
      else
        format.html { render action: "new" }
        format.json { render json: @casestudy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /casestudies/1
  # PUT /casestudies/1.json
  def update
    @casestudy = Casestudy.find(params[:id])

    respond_to do |format|
      if @casestudy.update_attributes(params[:casestudy])
        format.html { redirect_to admin_casestudy_path(@casestudy), notice: '成功案例更新完成。' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @casestudy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casestudies/1
  # DELETE /casestudies/1.json
  def destroy
    @casestudy = Casestudy.find(params[:id])
    @casestudy.destroy

    respond_to do |format|
      format.html { redirect_to admin_casestudies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/casestudies_controller.rb
class CasestudiesController < ApplicationController
	def index
		
		@casestudies = Casestudy.order( "created_at desc" ).all
	
		respond_to do | format |
			format.html
		end
	end
	
	def show
		
		@casestudy = Casestudy.find( params[ :id ] )
		@photos = @casestudy.photos.order( "created_at desc" )
		
		$metaDescription = @casestudy.content.length > 150 ? @casestudy.content[0..149] + "..." : @casestudy.content
		$metaTitle = @casestudy.title
		
		respond_to do | format |
			format.html
			format.json { render json: @casestudy }
		end		
	end
end

app/helpers/casestudies_helper.rb
module CasestudiesHelper
end

app/views/admin/casestudies/_form.html.erb
<script type="text/javascript">
	function checkForm() {
		var is_error = false;
		
		$("[name^=casestudy]").each(function() {
			if ( $(this).val().length <= 0 ) {
				is_error = true;
			}
		});
		
		if ( is_error ) {
			alert("請確認是否已完成填寫所有欄位。");
			return false;
		}
	}
</script>


  <%= stylesheet_link_tag "jquery.ui.datepicker" %>
  
<%= form_for([:admin, @casestudy]) do |f| %>
  <% if @casestudy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@casestudy.errors.count, "error") %> prohibited this casestudy from being saved:</h2>

      <ul>
      <% @casestudy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="main-title">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td valign="top" class="title" height="22" width="98"><%= @casestudy.created_at.nil? ? Time.now.to_s( :date ) : @casestudy.created_at.to_s( :date ) %></td>
      <td valign="middle" class="text"><%= f.text_field :title, :placeholder => "請輸入標題" %></td>
    </tr>
  </table>
</div>
<div class="main-text">
 <table width="100%" border="0" cellspacing="5" cellpadding="0">
    <tr>
      <th width="7%" align="left" valign="top"><%= f.label :subtitle, "副標" %></th>
      <td colspan="7" valign="top"><%= f.text_field :subtitle, :style => "width:98%" %></td>
    </tr>
    
    <tr>
      <th width="7%" align="left" valign="top"><%= f.label :client, "客戶" %></th>
      <td width="43%" valign="top"><%= f.text_field :client %></td>
      <th width="7%" align="left" valign="top">類別</th>
      <td width="43%" colspan="5" valign="top"><%= f.text_field :category  %></td>
    </tr>
    <tr>
      <th align="left" valign="top"><%= f.label :active_time, "時間" %></th>
      <td valign="top">
	      <%= f.text_field :active_time, :value => (@casestudy.active_time.to_s(:date) if !@casestudy.active_time.nil?), :style => "width: 114px;", :class => "datePicker", :placeholder => "請點擊後選取" %>~ 
	      <%= f.text_field :active_time_end, :value => (@casestudy.active_time_end.to_s(:date) if !@casestudy.active_time_end.nil?), :style => "width: 114px;", :class => "datePicker", :placeholder => "請點擊後選取"  %>
      </td>
      <th align="left" valign="top"><%= f.label :place, "地點" %></th>
      <td colspan="5" valign="top"><%= f.text_field :place %></td>
    </tr>
    <tr>
      <th align="left" valign="top"><%= f.label :invitation, "對象" %></th>
      <td valign="top"><%= f.text_field :invitation %></td>
      <th align="left" valign="top">&nbsp;</th>
      <td colspan="5" valign="top">&nbsp;</td>
    </tr>
    <th width="7%" align="left" valign="top"><%= f.label :content, "內文" %></th>
      <td colspan="7" valign="top"><%= f.text_area :content, :class => "autogrow" %></td>
  </table>

</div>

<div style="clear:both;">&nbsp;</div>
<div class="button"><img src="<%= image_path"save.png" %>" /><%= f.submit "儲存", :onClick => "return checkForm();" %></div>
<div class="button"><%= link_to admin_casestudies_path do %><img src="<%= image_path"cancel.png" %>" />取消<% end %></div>

<% end %>


<script type="text/javascript" >
	$('.datePicker').datepicker({ dateFormat: "yy-mm-dd" });
</script>

app/views/admin/casestudies/edit.html.erb
<%= render 'form' %>

<%= render 'admin/photos/form' %>

<%= render :partial => "admin/photos/list" %>

app/views/admin/casestudies/index.html.erb
<div class="button"><%= link_to new_admin_casestudy_path do %><img src="<%= image_path("add.png") %>" />新增案例<% end %></div>
<div class="main-list">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr class="main-list-title">
      <th width="15%" align="center" scope="col">日期</th>
      <th width="71%" align="left" scope="col">活動標題</th>
      <th width="7%" align="center" scope="col">編輯</th>
      <th width="7%" align="center" scope="col">刪除</th>
    </tr>
    <% @casestudies.each do |casestudy| %>
    <tr>
      <td align="center"> <%= casestudy.created_at.to_s( :date ) %> </td>
      <td align="left"><%= link_to casestudy.title, admin_casestudy_path(casestudy) %></td>
      <td align="center"><%= link_to edit_admin_casestudy_path(casestudy) do %><img src="<%= image_path("edit.png") %>" width="16" height="16" /><% end %></td>
      <td align="center"><%= link_to admin_casestudy_path(casestudy), method: :delete, data: { confirm: '確定刪除此案例？' } do %><img src="<%= image_path("delete.png") %>" /><% end %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/casestudies/new.html.erb
<%= render 'form' %>

<p id="newTip">＊新的案例必須在儲存建檔後才可上傳圖片。</p>

app/views/admin/casestudies/show.html.erb
<div class="main-title">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td valign="top" class="title" height="22" width="98"><%= @casestudy.active_time.to_s( :date ) %></td>
      <td valign="middle" class="text"><%= @casestudy.title %></td>
    </tr>
  </table>
</div>

    <div class="main-text">
    
      <table width="100%" border="0" cellspacing="5" cellpadding="0">
        <tr>
          <th width="7%" align="left" valign="top">副標</th>
          <td colspan="7" valign="top"><%= @casestudy.subtitle %></td>
        </tr>
        
        <tr>
          <th width="7%" align="left" valign="top">客戶</th>
          <td width="43%" valign="top"><%= @casestudy.client %></td>
          <th width="7%" align="left" valign="top">類別</th>
          <td width="43%" colspan="5" valign="top"><%= @casestudy.category %></td>
        </tr>
        <tr>
          <th align="left" valign="top">時間</th>
          <td valign="top"><%= @casestudy.active_time.to_s( :date_slashed ) %>~<%= @casestudy.active_time_end.to_s( :date_slashed ) %></td>
          <th align="left" valign="top">地點</th>
          <td colspan="5" valign="top"><%= @casestudy.place %></td>
        </tr>
        <tr>
          <th align="left" valign="top">對象</th>
          <td valign="top"><%= @casestudy.invitation %></td>
          <th align="left" valign="top">&nbsp;</th>
          <td colspan="5" valign="top">&nbsp;</td>
        </tr>
        
      </table>
      <div class="main-text"><%= @casestudy.content.gsub(/\n/, "<br />").html_safe %></div>      
</div>

    <div class="button"><%= link_to edit_admin_casestudy_path(@casestudy) do %><img src="<%= image_path("edit.png") %>" />編輯<% end %></div>
    <div class="button"><%= link_to admin_casestudies_path do %><img src="<%= image_path("back.png") %>" />返回<% end %></div>

	<p id="notice"><%= notice %></p>
	    
    <%= render :partial => "admin/photos/list" %>
    