config/routes.rb
Chesswin::Application.routes.draw do
  resources :casestudies
  resources :pages

  namespace :admin do 
  	resources :users 
  	resources :casestudies do
  		resources :photos
  	end
  	resources :photos
  end

  root :to => 'pages#index'

  
  match ':controller(/:action(/:id))(.:format)'
  
  match 'login'			=> 'users#login'
  match 'logout'		=> 'users#logout'
  
end

app/models/casestudy.rb
class Casestudy < ActiveRecord::Base
	has_many :photos
	attr_accessible :active_time, :active_time_end, :category, :client, :content, :invitation, :photos, :place, :subtitle, :title
end

app/controllers/admin/casestudies_controller.rb
#encoding: utf-8
class Admin::CasestudiesController < AdminController
  # GET /casestudies
  # GET /casestudies.json
  def index
    @casestudies = Casestudy.order( "created_at DESC" ).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @casestudies }
    end
  end

  # GET /casestudies/1
  # GET /casestudies/1.json
  def show
    @casestudy = Casestudy.find(params[:id])
    @photos = @casestudy.photos.order( :created_at )

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @casestudy }
    end
  end

  # GET /casestudies/new
  # GET /casestudies/new.json
  def new
    @casestudy = Casestudy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @casestudy }
    end
  end

  # GET /casestudies/1/edit
  def edit
    @casestudy = Casestudy.find(params[:id])
    @photos = @casestudy.photos.order( :created_at => "desc" )
  end

  # POST /casestudies
  # POST /casestudies.json
  def create
  
    @casestudy = Casestudy.new(params[:casestudy])

    respond_to do |format|
      if @casestudy.save
        format.html { redirect_to edit_admin_casestudy_path(@casestudy), notice: '成功案例建立完成。' }
        format.json { render json: @casestudy, status: :created, location: @casestudy }
      else
        format.html { render action: "new" }
        format.json { render json: @casestudy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /casestudies/1
  # PUT /casestudies/1.json
  def update
    @casestudy = Casestudy.find(params[:id])

    respond_to do |format|
      if @casestudy.update_attributes(params[:casestudy])
        format.html { redirect_to admin_casestudy_path(@casestudy), notice: '成功案例更新完成。' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @casestudy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casestudies/1
  # DELETE /casestudies/1.json
  def destroy
    @casestudy = Casestudy.find(params[:id])
    @casestudy.destroy

    respond_to do |format|
      format.html { redirect_to admin_casestudies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/casestudies_controller.rb
class CasestudiesController < ApplicationController
	def index
		
		@casestudies = Casestudy.order( "created_at desc" ).all
	
		respond_to do | format |
			format.html
		end
	end
	
	def show
		
		@casestudy = Casestudy.find( params[ :id ] )
		@photos = @casestudy.photos.order( "created_at desc" )
		
		$metaDescription = @casestudy.content.length > 150 ? @casestudy.content[0..149] + "..." : @casestudy.content
		$metaTitle = @casestudy.title
		
		respond_to do | format |
			format.html
			format.json { render json: @casestudy }
		end		
	end
end

app/helpers/casestudies_helper.rb
module CasestudiesHelper
end

app/views/casestudies/index.html.erb
<style>
	html{background:url(<%= image_path("case-01.gif") %>) repeat}
	body{font:300 15px "微軟正黑體";background:url(<%= image_path("header.png") %>) center 0 no-repeat transparent}
	footer{background:url(<%= image_path("footer-bg2.jpg") %>) top center no-repeat;}
	#container{background:url(<%= image_path("bg2.jpg") %>) 0 -50px no-repeat;}
	article ul{overflow:hidden;height:183px;width:951px;margin:0 auto 50px auto}
	article li{width:277px;height:162px;background:url(<%= image_path("case-03.jpg") %>) 0 0 no-repeat;float:left;-webkit-transition:all .5s ease;padding:20px 20px 0 20px}
	article li a{color:#d8d8d8;-webkit-transition:all .5s ease;-moz-transition:all .5s ease;}
	article li a:hover{text-decoration:none}
	hgroup{height:106px;font-size:14px}
	.info{height:26px;font-size:12px;padding:10px 0 0 0}
	.box1{border-bottom:1px solid #FCB732}
	.box1:hover a{color:#FCB732}
	.box2{border-bottom:1px solid #F16803}
	.box2:hover a{color:#F16803}
	.box3{border-bottom:1px solid #FD4444}
	.box3:hover a{color:#FD4444}
	.box4{border-bottom:1px solid #FF8076}
	.box4:hover a{color:#FF8076}
</style>

<h2><img src="<%= image_path("h2-case.png") %>" width="253" height="81"></h2>
<article>
<% 
	counter = 0
	@casestudies.each do | casestudy | 
	caseClass = counter > 3 ? "" : "case" + (counter % 4 + 1).to_s
	boxClass = "box" + (counter % 4 + 1).to_s
%>	
	<%= "<ul>".html_safe if counter % 3 == 0 %>
		<li class="<%= caseClass %> <%= boxClass %>">
			<a href="<%= url_for( casestudy ) %>">
			<hgroup>
			<h3><%= casestudy.title %></h3>
			<h4><%= casestudy.subtitle %></h4>
			</hgroup>
			<section class="info">
			<p class="com">
				<%= casestudy.invitation %>
			</p>
			<p class="type">
				<%= casestudy.place %>
			</p>
			</section>
			</a>
		</li>
	<%= "</ul>".html_safe if counter % 3 == 2 || counter == @casestudies.length - 1 %>	
<% 
	counter += 1
	end 
%>
</article>

app/views/casestudies/show.html.erb
<style>
	#bread-crumbs{background:url(<%= image_path("case-01.jpg") %>) 0 0 no-repeat;height:35px;border-radius:5px 5px 0px 0px;width:855px;margin:0 auto;color:#fff;padding:17px 0 0 20px}
	#bread-crumbs a,#article-footer a{color:#fff}
	
	article{width:785px;margin:0 auto;overflow:hidden;background:#fff;padding:35px 45px}
	hgroup{height:100px}
	h3{font:300 30px "微軟正黑體";color:#c74200}
	h4{font:300 18px "微軟正黑體";color:#c74200}
	#main{float:left;width:487px;line-height:28px}
	#main p{margin-bottom:30px}
	#info{float:right;color:#343434;font-size:13px;padding-left:15px;border-left:1px solid #aaa;line-height:25px;width:270px}
	
	#article-footer{background:url(<%= image_path("case-02.jpg") %>) 0 0 no-repeat;height:35px;border-radius:0px 0px 5px 5px ;width:855px;margin:0 auto;text-align:right;padding:17px 20px 0 0}
	#article-footer img{margin-right:10px;position:relative;top:2px}
	#image-list li{background:#fff;padding:10px}
	#image-list img{max-width:350px;height:auto;padding:3px;background:#fff;box-shadow:0 0 5px #777}
</style>

    <h2><img src="<%= image_path("h2-case.png") %>" width="253" height="81"></h2>
    <section id="bread-crumbs"><a href="<%= root_url %>">首頁</a> > <a href="<%= casestudies_path %>">成功案例</a> ></section>
    <article>
    <hgroup>
    <h3><%= @casestudy.title %></h3>
    <h4><%= @casestudy.subtitle %></h4>
    </hgroup>
    <section id="main">
    <p id="caseContent">
	    <%= @casestudy.content.gsub( /\n/, "<br />" ).html_safe %>
    </p>



<ul id="image-list">
	<% @photos.each do | photo | %>
	<li><img src="<%= photo.path.normal %>" width="350" height="234"></li>
	<% end %>
</ul>

    </section><!--main-->
    
    <section id="info">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="25%" align="left" valign="top">客戶名稱：</td>
    <td width="75%"><%= @casestudy.client %></td>
  </tr>
  <tr>
    <td align="left" valign="top">類　　別：</td>
    <td><%= @casestudy.category %></td>
  </tr>
  <tr>
    <td align="left" valign="top">活動時間：</td>
    <td><%= @casestudy.active_time.to_s( :date_slashed )  %>~<%= @casestudy.active_time_end.to_s( :date_slashed ) %></td>
  </tr>
  <tr>
    <td align="left" valign="top">活動地點：</td>
    <td><%= @casestudy.place %></td>
  </tr>
  <tr>
    <td align="left" valign="top">出席對象：</td>
    <td><%= @casestudy.invitation %></td>
  </tr>
</table>

    </section><!--info-->    
    
     </article>
    <section id="article-footer"><a href="<%= casestudies_path %>"><img src="<%= image_path("case-05.png") %>" width="14" height="14">回成功案例列表</a></section>


<script type="text/javascript">
	$('p#caseContent').html($('p#caseContent').html().replace(/(https?:\/\/[a-zA-Z0-9\.\-\/]+)/g, '<a href="$1" target="_blank">$1</a>'));
</script>