config/routes.rb
Chesswin::Application.routes.draw do
  resources :casestudies
  resources :pages

  namespace :admin do 
  	resources :users 
  	resources :casestudies do
  		resources :photos
  	end
  	resources :photos
  end

  root :to => 'pages#index'

  
  match ':controller(/:action(/:id))(.:format)'
  
  match 'login'			=> 'users#login'
  match 'logout'		=> 'users#logout'
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :casestudy
	
	attr_accessible :casestudy_id, :description, :ext, :stauts, :path
	mount_uploader :path, CasestudiesUploader
end

app/controllers/admin/photos_controller.rb
#encoding: utf-8
class Admin::PhotosController < AdminController
	before_filter :get_casestudy
	layout "simple"

	def index
		@photos = @casestudy.photos.all( :order => "updated_at DESC" )
		@photo = Photo.new
		respond_to do | format |
			format.html
			format.json { render json: @photos }
		end
	end
	
	def new
		
		@photo = Photo.new
		
		respond_to do | format |
			format.html
		end
		
	end
	
	def show
		@photo = Photo.find( params[ :id ] )
		
		respond_to do | format |
			format.html
			format.json { render json: @photo }
		end
	end
	
	def create
		
		@photo = @casestudy.photos.build( params[ :photo ] )
		respond_to do | format |
		
			if @photo.save && @photo.path.length != 0
				
				# 將id塞回檔名
				@photo.update_attribute('path', "#{@photo.id}#{@photo.path}")		
				
				format.html { redirect_to edit_admin_casestudy_path(@casestudy) + "#fileUploader", :notice => "圖片建立完成" }
				format.json { render json: @photo, status: :created, location => @photo }	
							
			else
				
				@errors = ''
				@photo.destroy
				
				if @photo.path.length == 0 then @errors += "檔案格式錯誤" end
				
				format.html { render action: "new", :notice => '圖片上傳失敗' }
				format.json { render json: params, status: :unprocessable_entity }
				
			end
			 
		end			
	end
	
	def destroy
		@photo = Photo.find( params[ :id ] )
		@photo.destroy
		
		respond_to do | format |
			format.html { redirect_to admin_casestudy_path(@casestudy) , :notice => '圖片刪除完成'}
			format.json { head :no_content }
			format.js
		end
	end

private
	def get_casestudy
		@casestudy = Casestudy.find( params[ :casestudy_id ] )
	end

end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/views/admin/photos/_form.html.erb
<% if notice || @errors != '' %>
	<p class="warning">
		<%= notice %>
		<br>
		<%= @errors %>
	</p>
<% end %>



<%= stylesheet_link_tag "filedrop" %>
<h2 style="clear:both">上傳圖片</h2>
<form id="fileForm" method="post" enctype="multipart/form-data" action="<%= admin_casestudy_photos_path( @casestudy )  %>">
	<input id="fileUploader" type="file" name="photo[path]" style="" />
	<input name="authenticity_token" type="hidden" value="<%= session[ :_csrf_token ] %>" />
	<input id="fileSubmit" type="submit" value="上傳檔案" />
	<p class="alert" style="color: #900; font-weight: 600;">＊若您的瀏覽器不支援非同步上傳，請使用一般上傳模式。</p>
</form>
<div class="main-upload" id="dropbox">
</div>



<script type="text/javascript">

$(function(){
	
	var dropbox = $('#dropbox'),
		message = $('.message', dropbox);
		
	dropbox.filedrop({
		// The name of the $_FILES entry:
		paramname:'photo[path]',
		data: { authenticity_token : "<%= session[ :_csrf_token ] %>" },
		// data: { authenticity_token : $('input[name=authenticity_token]').val() },
		maxfiles: 5,
    	maxfilesize: 2,
		url: '<%= admin_casestudy_photos_path( @casestudy ) + ".json" %>',
		
		uploadFinished:function(i,file,response){
			$.data(file).addClass('done');
			// response is the JSON object that post_file.php returns
		},
		
    	error: function(err, file) {
			switch(err) {
				case 'BrowserNotSupported':					
					break;
				case 'TooManyFiles':
					alert('Too many files! Please select 5 at most! (configurable)');
					break;
				case 'FileTooLarge':
					alert(file.name+' is too large! Please upload files up to 2mb.');
					break;
				default:
					break;
			}
		},
		
		rename: function(string) {
			return "image." + string.split('.').pop();
		},
		
		// Called before each upload is started
		beforeEach: function(file){
			if(!file.type.match(/^image\//)){
				alert('Only images are allowed!');
				
				// Returning false will cause the
				// file to be rejected
				return false;
			}
		},
		
		uploadStarted:function(i, file, len){
			createImage(file);
		},
		
		progressUpdated: function(i, file, progress) {
			$.data(file).find('.progress').width(progress);
		}
    	 
	});
	
	var template = '<div class="preview">'+
						'<span class="imageHolder">'+
							'<img />'+
							'<span class="uploaded"></span>'+
						'</span>'+
						'<div class="progressHolder">'+
							'<div class="progress"></div>'+
						'</div>'+
					'</div>'; 
	
	
	function createImage(file){

		var preview = $(template), 
			image = $('img', preview);
			
		var reader = new FileReader();
		
		image.width = 100;
		image.height = 100;
		
		reader.onload = function(e){
			
			// e.target.result holds the DataURL which
			// can be used as a source of the image:
			
			image.attr('src',e.target.result);
		};
		
		// Reading the file as a DataURL. When finished,
		// this will trigger the onload function above:
		reader.readAsDataURL(file);
		
		message.hide();
		preview.appendTo(dropbox);
		
		// Associating a preview container
		// with the file, using jQuery's $.data():
		
		$.data(file,preview);
	}

	function showMessage(msg){
		message.html(msg);
	}
	
});

</script>

app/views/admin/photos/_list.html.erb
<h2 style="clear:both">圖片列表</h2>
<div class="main-data">
<ul>
<% @photos.each do | photo | %>
    <li data-pid="<%= photo.id %>"><img src="<%= photo.path.normal %>"/>
	    <%= link_to admin_casestudy_photo_path(@casestudy, photo), :method => :delete, data: { confirm: '確定刪除圖片？' }, remote: true do %>
	    	<img src="<%= image_path("delete-img.png") %>"/>
	    <% end %>
    </li>
<% end %>
</ul>
</div>

app/views/admin/photos/destroy.js.erb
$('[data-pid=<%= @photo.id %>]').fadeOut();

app/views/admin/photos/index.html.erb
<%= stylesheet_link_tag "filedrop" %>

<%= render :partial => 'form' %>


<%#= link_to '建立新圖片', new_admin_casestudy_photo_path( @casestudy ) %>

<div id="imgTemplate" style="display: none">
	<div style="float:left; margin: 20px;">
			<dt></dt>
			<dd><img height="240" src="" /></dd>
	</div>	
</div>

<dl>
<% @photos.each do | photo | %>
	<div style="float:left; margin: 20px;">
		<dt>Updated_at: <%= photo.updated_at %> | <%= link_to 'Delete', admin_casestudy_photo_path(@casestudy, photo), :method => :delete, data: { confirm: "確定要刪除此圖片？" } %></dt>
		<dd><img height="240" src="<%= photo.path %>" /></dd>
	</div>
<% end %>
</dl>

app/views/admin/photos/new.html.erb
<%= render 'form' %>

app/views/admin/photos/show.html.erb
<% if notice %>
	<p class="warning"><%= notice %></p>
<% end %>

<img src="<%= @photo.path %>" />