config/routes.rb
Chesswin::Application.routes.draw do
  resources :casestudies
  resources :pages

  namespace :admin do 
  	resources :users 
  	resources :casestudies do
  		resources :photos
  	end
  	resources :photos
  end

  root :to => 'pages#index'

  
  match ':controller(/:action(/:id))(.:format)'
  
  match 'login'			=> 'users#login'
  match 'logout'		=> 'users#logout'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :username, :name
  validates_presence_of :password, :username, :name
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @user = User.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit  	
    @user = User.find(params[:id])
  	render :layout => "admin_narrow"
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.password = encrypt_password(@user.password)
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: 'User was successfully created.' }
        format.json { render json: [:admin, @user], status: :created, location: @user }
      else
      	@users = User.all
      	
        format.html { render action: "index" }
        format.json { render json: [:admin, @user].errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    
    params[:user]['password'] = encrypt_password(params[:user]['password'] )
    
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_users_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: [:admin, @user].errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
      respond_to do |format|
	  	if User.all.length <= 1 
	  	
		    format.html { redirect_to admin_users_url, :notice => 'You cannot kill all user.' }
		    format.json { head :no_content }
	  	else 			  	
		    @user = User.find(params[:id])
		    @user.destroy
		    
		    format.html { redirect_to admin_users_url }
		    format.json { head :no_content }
	  	end
    end
  end
  
private
	def encrypt_password( password )
		if password.length() <= 0 then return false end
		 
		return Digest::SHA1.hexdigest( password )
		 
	end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  layout "admin_narrow"
  
  def login
  	respond_to do | format |
  		if session[ :user ].nil?
	  		@user = User.new
  			format.html
  		else
  			format.html { redirect_to :controller => :admin }
  		end
  	end
  
  end
  
  def logout
  	
  	session[ :user ] = nil
  	
  	respond_to do | format |
  		format.html { redirect_to root_url + 'login', :notice => "Logout Successfully." }
  	end
  	
  end
  
  # 取得登入授權
  def get_permission
	 
	 @user = params[ :user ]
	 
	 searchUser = User.where( :username => @user['username'], :password => Digest::SHA1.hexdigest( @user['password'] ) ).first
	  
	  respond_to do | format |		  	
		  if searchUser
		  	# 更新使用者登入時間
		  	searchUser[ :last_login ] = DateTime.now
		  	searchUser.save
		  	
		  	session[ :user ] = searchUser
		  	session[ :user ][ :password ] = '**hidden**'
		  	params[ :session ] = session
		  	
		  	if params[ :redirect ].length <= 0
		  		format.html { redirect_to :controller => :admin }
		  	else
		  		format.html { redirect_to params[ :redirect ] }
		  	end
		  	
		  else
		  	
		  	format.html { redirect_to root_url + 'login', :notice => 'Username not found or wrong password' }
		  	format.json { render json: searchUser, status: :unprocessable_entity }
		  	
		  end
	  end
	  
	  
	  
	  
	  
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<script type="text/javascript">
	
	function checkForm() {
		var is_error = false;
		var errors = "";
		
		$("input[id^=user]").each( function() {
			if ( $(this).val().length <= 0 ) {
				is_error = true;
				errors += $("label[for=" + $(this).attr('id') + "]").html() + "不得為空\n";
			}			
			
			
		} );
		
		if ( $("#passwordConfirm").val() != $("#user_password").val() ) {
				is_error = true;
				errors += "請重新檢查密碼\n";			
		}
		
		if ( is_error ) {
			alert(errors);
			return false;
		}
	}
	
</script>

<div class="main-text">
<%= form_for([:admin, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
	  <tr>
	    <th width="10%"><%= f.label :name, "姓名" %></th>
	    <td width="20%"><%= f.text_field :name, :placeholder => "請輸入使用者姓名" %></td>
	    <th width="10%"><%= f.label :username, "帳號" %></th>
	    <td width="60%"><%= f.text_field :username, :placeholder => "請輸入使用者登入帳號" %></td>
	  </tr>
	</table>
	
	<table width="100%" border="0" cellspacing="0" cellpadding="0" style="margin-top:10px">
	  <tr>
	    <th width="10%"><%= f.label :password, "密碼" %></th>
	    <td width="37%"><%= f.password_field :password, :placeholder => "請輸入密碼" %></td>
	    <th width="15%">確認密碼</th>
	    <td width="38%"><input id="passwordConfirm" type="password" placeholder="請再次輸入密碼" name="textfield" /></td>
	  </tr>
	</table>	
</div>
<div class="button"><img src="<%= image_path("add.png") %>"><%= f.submit "新增帳號", :onClick => "return checkForm();" %></div>
<% end %>

app/views/admin/users/edit.html.erb
<script type="text/javascript">
	
	function checkForm() {
		var is_error = false;
		var errors = "";
		
		$("input[id^=user]").each( function() {
			if ( $(this).val().length <= 0 ) {
				is_error = true;
				errors += $("label[for=" + $(this).attr('id') + "]").html() + "不得為空\n";
			}			
			
			
		} );
		
		if ( $("#passwordConfirm").val() != $("#user_password").val() ) {
				is_error = true;
				errors += "請重新檢查密碼\n";			
		}
		
		if ( is_error ) {
			alert(errors);
			return false;
		}
	}
	
</script>

<h2><img src="<%= image_path("psw.png") %>" width="16" height="16" /> 重設您的密碼</h2>
<%= form_for([:admin, @user]) do | f | %>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="left"><%= f.label :password, "請輸入新密碼" %><br>
      <%= f.password_field :password, :placeholder => "請輸入密碼", :value => "" %></td>
  </tr>
  <tr>
    <td align="left">再次確認新密碼<br>
      <input type="password" name="textfield" id="passwordConfirm" placeholder="請再次輸入密碼" /></td>
  </tr>
</table>
<div class="button">
  <input name="" type="button" />
  <%= f.submit "變更", :onClick => "return checkForm();" do %><img src="<%= image_path("check.png") %>" /><% end %></div>
</div>
  
<% end %>

app/views/admin/users/index.html.erb
    <%= render :partial => "form" %>
    
    <p id="notice"><%= notice %></p>
    
    <!--main-text-->
    <div class="main-list">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr class="main-list-title">
          <th width="17%" align="center" scope="col">姓名</th>
          <th width="75%" align="left" scope="col">帳號</th>
          <th width="8%" align="center" scope="col">刪除</th>
        </tr>
        <% @users.each do |user| %>
        <tr>
          <td align="center"><%= user.name %></td>
          <td align="left"><%= user.username %></td>
          <td align="center"><%= link_to [:admin, user], method: :delete, data: { confirm: "確定刪除" + user.name + "?" } do %><img src="<%= image_path( "delete.png" ) %>"><% end %></td>
        </tr>
        <% end %>
      </table>
    </div>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Last login:</b>
  <%= @user.last_login %>
</p>


<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>